matrix:
    include:
      - language: python
        python:
          - 2.7
          - 3.6
        before_install:
          - sudo apt-get install -y python-numpy
          - pip install tensorflow
          - pip install codecov
          - pip install pytest-cov
        # command to run tests
        script:
          - pytest

        after_sucess:
          - codecov
      - language: r
        before_install:
          - cd r/lad
        r:
          - release
          - devel
        cache: packages
        r_packages: testthat
        install:
          - R -e 'devtools::install_deps(dep = T)'

        script:
          - R CMD build .
          - R CMD check *tar.gz
