build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36-x64

platform:
  - x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"
  - where conda
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - "conda create -q -n test-environment python=%PYTHON_VERSION% conda-build numpy"
  - activate test-environment
  - pip install --upgrade tensorflow
  - "cd python"

test_script:
  - "python setup.py test"
